# Generated by Django 4.1.3 on 2022-11-14 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_student_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='student',
            new_name='users',
        ),
    ]
